version: '3'
services:
  db:
    image: postgres
    container_name: iceberg-postgres-alikumbul
    restart: always
    environment:
      POSTGRES_USER: iceberguser
      POSTGRES_PASSWORD: icebergpass
      POSTGRES_DB: icebergdb
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data